spring.application.name=javagrunt-cli
logging.level.root=off
spring.main.banner-mode=off
spring.main.web-application-type=none
spring.shell.history.enabled=false
spring.shell.interactive.enabled=true
