Args = --initialize-at-run-time=org.openrewrite.internal.EncodingDetectingInputStream \
       --initialize-at-run-time=org.openrewrite.xml.XmlParser \
       --initialize-at-run-time=org.openrewrite.maven.MavenParser \
       --initialize-at-run-time=org.openrewrite.java.JavaParser \
       --initialize-at-run-time=org.openrewrite.Parser \
       --initialize-at-build-time=org.openrewrite.Recipe \
       -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       --enable-url-protocols=http,https \
       --enable-all-security-services
